#+TITLE: My Notebook
#+AUTHOR: Liyun Dai (dailiyun2009@163.com)
#+EMAIL: dailiyun2009@163.com


* Ubuntu connect internet by command
<2018-10-08 一>
1. List all interface command
#+BEGIN_SRC  shell
 ifconfig -a
#+END_SRC

2. Start one interface
#+BEGIN_SRC  shell
sudo ifconfig [eth0] up
#+END_SRC
3. Close one interface 
#+BEGIN_SRC  shell
sudo ifconfig [eth0] down
#+END_SRC
4. Scan all available wifi 
#+BEGIN_SRC  shell
sudo iw dev [wlan0] scan | less
#+END_SRC
5. Connect a wifi without password 
#+BEGIN_SRC  shell
sudo iw dev [wlan0] connect [ssid]
#+END_SRC

6. Connect a wifi with WEP mode password  
#+BEGIN_SRC  shell
sudo iw dev [wlan0]  key 0:[password]
#+END_SRC
7. Connect a widi with WAP mode password 
  + Generate wap config file 
   #+BEGIN_SRC  shell
   wpa_passphrase [ssid] [password] > wpa.conf
   #+END_SRC
  + Connect internet 
   #+BEGIN_SRC  shell
   wpa_supplicant -i [wlan0] -B -c ./wpa.conf
   #+END_SRC
  + Obtain ip adress
   #+BEGIN_SRC  shell
   dhclient [wlan0]
   #+END_SRC


* Begining Linux Programming 4th Edition
<2018-10-08 一>
** Getting Started
UNIX Philosophy
+ Simplicity
+ Focus
+ Resuable Components
+ Filters

+ Open File Formats
Util envoroment variables
+ Execute search paths PATH
   #+BEGIN_SRC  sh :results output
echo $PATH
   #+END_SRC

   #+RESULTS:
   : /home/yun/bin:/home/yun/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/yun/bin:/home/yun/jdk1.8.0_181/bin

+ Generate static link lib
  #+BEGIN_SRC  sh :results output
ar crv libfoo.a bill.o fred.o
randlib libfoo.a
  #+END_SRC


** Shell Programming
1. If you prefer to capture both sets of output into a single file, you can use the >& operator to combine the
two outputs. Therefore,
  #+BEGIN_SRC  sh :results output
kill -HUP 1234 >killout.txt 2>killerr.txt
  #+END_SRC


2. If you prefer to capture both sets of output into a single file, you can use the >& operator to combine the
two outputs. Therefore,
  #+BEGIN_SRC  sh :results output
kill -1 1234 >killouterr.txt 2>&1
  #+END_SRC

3. Useful Environment variable
+ $0 The name of the shell script
+ $# The number of parameters passed
+ \$ \$ The process ID of the shell script, often used inside a script for generating unique temporary filenames; for example /tmp/tmpfile_$$

4. That looks good, except that you also find the current directory, which you didn’t want. You were inter-
ested only in regular files, so you add an additional test , -type f :
  #+BEGIN_SRC  sh :results output
find . -newer while2 -type f 
  #+END_SRC

5. Now find files that either start with an underscore or are newer than the file while2 , but must in either
case be regular files. This will show you how to combine tests using parentheses:

  #+BEGIN_SRC  sh :results output
find . \( -name “_*“ -or -newer while2 \) -type f
  #+END_SRC





* ssh login with out password
<2018-10-11 四>
There are two PCs A and  B. B wants to login in A without
password throud ssh 
1. Run following command on B 
   #+BEGIN_SRC  shell
 ssh-keygen -t rsa -P ''
   #+END_SRC
2. Copy the key of B to A
 +   Genertate ssh key
  #+BEGIN_SRC  shell
 scp .ssh/id_rsa.pub to [usr]@[A ip]:~/
   #+END_SRC
 + Add B's ssh key to authorized_keys on A
  #+BEGIN_SRC  shell
 cat id_rsa.pub >> .ssh/authorized_keys
  #+END_SRC





* English paper common wrong usage

   + +In section+ ->  In Section
   + +at the begining+ -> in the begining 
   + +an univariate polynomial+ -> a univariate polynomial
   + +By assumption xxx+ -> By assumption, xxx
   + +I.e+ -> I.e.,  



* Java non-static inner class has implict reference for outer class
**  http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2014/1106/1922.html
** https://blog.csdn.net/zmx729618/article/details/54093532

* Online JudgeMent seminar
** Tingtine Test online editor
<2018-10-15 一>
+ Test id not start 1
+ Choice test want to inset figure 
+ flush to save to data
+ settting point for evert test
** xuelian
+ Lige abstact syntax tree (AST)
+ Data-inconsistent Java

